closure:
  lizard: 1.17.3
links:
  - name: lizard-1.17.3-py2.py3-none-any.whl
    sha256: 178z7a58lqlsvx51m674lcwa4cidvkf0rbwdpgs9rms3iplmnafp
    url: https://pypi.org/packages/py2.py3/l/lizard/lizard-1.17.3-py2.py3-none-any.whl
  - name: lizard-1.17.3.tar.gz
    sha256: 1578q2vgnlm9bxwmbap3ffkhb551ml13yq5ffc4yhya9q3zlx691
    url: https://pypi.org/packages/source/l/lizard/lizard-1.17.3.tar.gz
python: "3.8"
