# SPDX-FileCopyrightText: 2022 Fluid Attacks and Makes contributors
#
# SPDX-License-Identifier: MIT

---
steps:
  - label: step-1
    command: echo "step-1"
  - label: step-2
    command: echo "step-2"
  - label: step-3
    command: echo "step-3"
