jobs:
  formatBash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fluidattacks/makes@main
      name: formatBash
      with:
        args: m .formatBash
  formatPython:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fluidattacks/makes@main
      name: formatPython
      with:
        args: m .formatPython
  helloWorld:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fluidattacks/makes@main
      name: helloWorld
      with:
        args: m .helloWorld
  lintBash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fluidattacks/makes@main
      name: lintBash
      with:
        args: m .lintBash
name: Makes
on:
  pull_request:
    branches: [ main ]
