jobs:
  formatBash:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fluidattacks/makes@main
      with:
        args: m .formatBash
  helloWorld:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fluidattacks/makes@main
      with:
        args: m .helloWorld
name: CI
on:
  pull_request:
    branches: [ main ]
