jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: __all__
      with:
        args: sh -c "nix-env -if . && m __all__"
  formatBash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /formatBash
      with:
        args: sh -c "nix-env -if . && m /formatBash"
  formatMarkdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /formatMarkdown
      with:
        args: sh -c "nix-env -if . && m /formatMarkdown"
  formatNix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /formatNix
      with:
        args: sh -c "nix-env -if . && m /formatNix"
  formatPython:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /formatPython
      with:
        args: sh -c "nix-env -if . && m /formatPython"
  helloWorld:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /helloWorld
      with:
        args: sh -c "nix-env -if . && m /helloWorld"
  lintBash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /lintBash
      with:
        args: sh -c "nix-env -if . && m /lintBash"
  lintCommitMsg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /lintCommitMsg
      with:
        args: sh -c "nix-env -if . && m /lintCommitMsg"
  lintMarkdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /lintMarkdown
      with:
        args: sh -c "nix-env -if . && m /lintMarkdown"
  lintNix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /lintNix
      with:
        args: sh -c "nix-env -if . && m /lintNix"
  lintPython_dirOfModules_makes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /lintPython/dirOfModules/makes
      with:
        args: sh -c "nix-env -if . && m /lintPython/dirOfModules/makes"
  lintPython_dirOfModules_makes_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /lintPython/dirOfModules/makes/main
      with:
        args: sh -c "nix-env -if . && m /lintPython/dirOfModules/makes/main"
  lintPython_module_cliMain:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /lintPython/module/cliMain
      with:
        args: sh -c "nix-env -if . && m /lintPython/module/cliMain"
name: dev
on:
  pull_request:
    branches: [ main ]
