jobs:
  formatBash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /formatBash
      with:
        args: sh -c "nix-env -if . && m /formatBash"
  formatNix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /formatNix
      with:
        args: sh -c "nix-env -if . && m /formatNix"
  formatPython:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /formatPython
      with:
        args: sh -c "nix-env -if . && m /formatPython"
  helloWorld:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /helloWorld
      with:
        args: sh -c "nix-env -if . && m /helloWorld"
  lintBash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /lintBash
      with:
        args: sh -c "nix-env -if . && m /lintBash"
  lintNix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /lintNix
      with:
        args: sh -c "nix-env -if . && m /lintNix"
  lintPython_module_cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      name: /lintPython/module/cli
      with:
        args: sh -c "nix-env -if . && m /lintPython/module/cli"
name: dev
on:
  pull_request:
    branches: [ main ]
