jobs:
  deployContainerImage_makesGitHub:
    if: ${{ github.repository == 'fluidattacks/makes' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://docker.io/nixos/nix:2.3.12
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
      with:
        args: sh -c "nix-env -if . && m . /deployContainerImage/makesGitHub"
  deployContainerImage_makesGitHubMonthly:
    if: ${{ github.repository == 'fluidattacks/makes' }}
    needs: deployContainerImage_makesGitHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://ghcr.io/fluidattacks/makes:main
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
      with:
        args: m . /deployContainerImage/makesGitHubMonthly
name: prod
on:
  push:
    branches: [ main ]
