jobs:
  releaseTableOfContents:
    if: ${{ github.repository == 'fluidattacks/makes' }}
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          COMMIT_EMAIL: help@fluidattacks.com
          COMMIT_MESSAGE: "feat(doc): #0 update table of contents"
          COMMIT_NAME: Fluid Attacks
          TOC_TITLE: "# Contents"
  releaseGitHub:
    if: ${{ github.repository == 'fluidattacks/makes' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: richardsimko/update-tag@v1
      with:
        tag_name: 21.08
      env:
        GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
    - uses: johnwbyrd/update-release@v1.0.0
      with:
        files: README.md
        release: 21.08
        prerelease: true
        tag: 21.08
        token: ${{ secrets._GITHUB_TOKEN }}
name: release
on:
  push:
    branches: [ main ]
