jobs:
  releaseTableOfContents:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          COMMIT_EMAIL: help@fluidattacks.com
          COMMIT_MESSAGE: "feat(doc): update table of contents"
          COMMIT_NAME: Fluid Attacks
          TOC_TITLE: "# Contents"
  releaseGitHub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@1.1.1
      id: tag
      env:
        GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
      with:
        root: ./README.md
        regex_pattern: "# Makes v(.*)"
    - uses: actions/create-release@v1
      if: ${{ steps.tag.outputs.tagcreated == 'yes' }}
      env:
        GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
      with:
        release_name: ${{ steps.tag.outputs.version }}
        tag_name: ${{ steps.tag.outputs.version }}
name: Release
on:
  push:
    branches: [ main ]
